name: CI
on:
  push:
    branches: [main]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install Dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: 174.138.5.242
          username: root
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: 
            cd /home/demo-git-actions-nest-mongo
            git pull
            /usr/local/bin/pm2 restart demo-mongo

