name: CI
on:
  push:
    branches: [master]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: ${{secrets.NODE_VERSION}}
      - name: Install Dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: cd ${{secrets.PROJECT_FOLDER}} &&
            git pull https://${{secrets.GIT_ACCOUNT_USERNAME}}:${{secrets.GIT_ACCOUNT_PASSWORD}}@${{secrets.GIT_URL}} ${{secrets.GIT_BRANCH_NAME}}&&
            npm run build && /usr/local/bin/pm2 restart ${{secrets.PM2_APP_NAME}}
